import { Resident, RiskCategory, PropertyMeta, TrendDataPoint } from './types';

export const propertyMeta: Record<string, PropertyMeta> = {
  'Greystar @ The Pines': {
    name: 'Greystar @ The Pines',
    strategy: 'occupancy',
    rentControlPct: 0.03,
    occupancyRate: 0.88,
    targetOccupancy: 0.92,
  },
  'Greystar @ Riverside': {
    name: 'Greystar @ Riverside',
    strategy: 'revenue',
    rentControlPct: null,
    occupancyRate: 0.95,
    targetOccupancy: 0.92,
  },
  'Greystar @ Midtown': {
    name: 'Greystar @ Midtown',
    strategy: 'revenue',
    rentControlPct: 0.05,
    occupancyRate: 0.93,
    targetOccupancy: 0.92,
  },
};

export const portfolioTrends: TrendDataPoint[] = [
  { month: "Nov '25", rentRoll: 32800, avgScore: 67, renewalRate: 0.72, occupancy: 0.89, isProjection: false },
  { month: "Dec '25", rentRoll: 33100, avgScore: 65, renewalRate: 0.75, occupancy: 0.90, isProjection: false },
  { month: "Jan '26", rentRoll: 33400, avgScore: 63, renewalRate: 0.78, occupancy: 0.91, isProjection: false },
  { month: "Feb '26", rentRoll: 33700, avgScore: 62, renewalRate: 0.79, occupancy: 0.91, isProjection: false },
  { month: "Mar '26", rentRoll: 34100, avgScore: 61, renewalRate: 0.80, occupancy: 0.92, isProjection: false },
  { month: "Apr '26", rentRoll: 34350, avgScore: 61, renewalRate: 0.80, occupancy: 0.92, isProjection: false },
  { month: "May '26", rentRoll: 34500, avgScore: 61, renewalRate: 0.80, occupancy: 0.92, isProjection: false },
  { month: "Jun '26", rentRoll: 34900, avgScore: 58, renewalRate: 0.82, occupancy: 0.93, isProjection: true },
  { month: "Jul '26", rentRoll: 35300, avgScore: 55, renewalRate: 0.83, occupancy: 0.93, isProjection: true },
  { month: "Aug '26", rentRoll: 35600, avgScore: 53, renewalRate: 0.84, occupancy: 0.94, isProjection: true },
  { month: "Sep '26", rentRoll: 35900, avgScore: 51, renewalRate: 0.85, occupancy: 0.94, isProjection: true },
  { month: "Oct '26", rentRoll: 36200, avgScore: 49, renewalRate: 0.86, occupancy: 0.95, isProjection: true },
];

function riskCategory(score: number): RiskCategory {
  if (score >= 75) return 'very-high';
  if (score >= 50) return 'high';
  if (score >= 25) return 'medium';
  return 'low';
}

export const residents: Resident[] = [
  {
    id: 'r001',
    name: 'Marcus Webb',
    unit: '4B',
    property: 'Greystar @ The Pines',
    leaseEndDate: '2025-06-30',
    monthlyRent: 2850,
    riskScore: 88,
    riskCategory: riskCategory(88),
    retentionVerdict: 'conditional',
    retentionRationale:
      'High earner with 3-year tenure. Retention is worth attempting with a targeted concession, but maintenance issues must be resolved first.',
    lifetimeValue: 34200,
    riskFactors: [
      {
        key: 'open_work_orders',
        label: 'Open Work Orders',
        value: '6 unresolved',
        impact: 'negative',
        weight: 0.92,
        description: '6 open maintenance tickets, 2 over 30 days old. Top driver of dissatisfaction.',
      },
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+11%',
        impact: 'negative',
        weight: 0.78,
        description: 'Proposed 11% increase is above market average of 6% for this zip code.',
      },
      {
        key: 'days_since_contact',
        label: 'Days Since Last Contact',
        value: '47 days',
        impact: 'negative',
        weight: 0.55,
        description: 'No outreach from leasing team in 47 days. Resident feels ignored.',
      },
      {
        key: 'late_payments',
        label: 'Late Payments (12mo)',
        value: '1',
        impact: 'neutral',
        weight: 0.15,
        description: '1 late payment in the last 12 months — minor signal.',
      },
      {
        key: 'tenure',
        label: 'Tenure',
        value: '3 years',
        impact: 'positive',
        weight: 0.40,
        description: 'Long tenure suggests attachment to the community.',
      },
    ],
    actionItems: [
      {
        id: 'a001-1',
        priority: 'urgent',
        action: 'Resolve all open work orders within 5 business days',
        owner: 'Maintenance Team',
        dueInDays: 5,
      },
      {
        id: 'a001-2',
        priority: 'urgent',
        action: 'Call resident to personally acknowledge service delays',
        owner: 'Leasing Manager',
        dueInDays: 2,
      },
      {
        id: 'a001-3',
        priority: 'high',
        action: 'Offer 1-month rent concession or cap increase at 6%',
        owner: 'Leasing Agent',
        dueInDays: 7,
      },
    ],
  },
  {
    id: 'r002',
    name: 'Priya Nair',
    unit: '12A',
    property: 'Greystar @ Riverside',
    leaseEndDate: '2025-07-31',
    monthlyRent: 1950,
    riskScore: 82,
    riskCategory: riskCategory(82),
    retentionVerdict: 'yes',
    retentionRationale:
      'Perfect payment history and 4-year tenure. High retention value — a small concession will likely close renewal.',
    lifetimeValue: 23400,
    riskFactors: [
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+14%',
        impact: 'negative',
        weight: 0.88,
        description: 'Proposed 14% increase is significantly above market. Primary churn driver.',
      },
      {
        key: 'app_engagement',
        label: 'App Engagement',
        value: 'Low (9 sessions/mo)',
        impact: 'negative',
        weight: 0.45,
        description: 'Below-average resident portal activity — infrequent login, no partner offer interactions.',
      },
      {
        key: 'open_work_orders',
        label: 'Open Work Orders',
        value: '1 unresolved',
        impact: 'negative',
        weight: 0.30,
        description: 'Minor open ticket — HVAC filter replacement pending 18 days.',
      },
      {
        key: 'late_payments',
        label: 'Late Payments (12mo)',
        value: '0',
        impact: 'positive',
        weight: 0.50,
        description: 'Perfect payment history — a very strong retention signal.',
      },
      {
        key: 'tenure',
        label: 'Tenure',
        value: '4 years',
        impact: 'positive',
        weight: 0.60,
        description: 'Four-year tenure shows strong attachment to the property.',
      },
    ],
    actionItems: [
      {
        id: 'a002-1',
        priority: 'urgent',
        action: 'Cap rent increase at 7% and present to resident with loyalty framing',
        owner: 'Leasing Agent',
        dueInDays: 3,
      },
      {
        id: 'a002-2',
        priority: 'high',
        action: 'Resolve HVAC work order and send follow-up confirmation',
        owner: 'Maintenance Team',
        dueInDays: 5,
      },
      {
        id: 'a002-3',
        priority: 'medium',
        action: 'Push targeted Uber Eats or partner offer via app to re-engage resident',
        owner: 'Community Manager',
        dueInDays: 14,
      },
    ],
  },
  {
    id: 'r003',
    name: 'Derek Hollis',
    unit: '2C',
    property: 'Greystar @ The Pines',
    leaseEndDate: '2025-08-31',
    monthlyRent: 3200,
    riskScore: 79,
    riskCategory: riskCategory(79),
    retentionVerdict: 'yes',
    retentionRationale:
      'Highest-rent unit in the cohort. Retention ROI is very strong — prioritize this resident.',
    lifetimeValue: 38400,
    riskFactors: [
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+9%',
        impact: 'negative',
        weight: 0.65,
        description: 'Proposed increase at the high end of market range.',
      },
      {
        key: 'days_since_contact',
        label: 'Days Since Last Contact',
        value: '38 days',
        impact: 'negative',
        weight: 0.50,
        description: 'No resolution communicated after complaint filings.',
      },
      {
        key: 'late_payments',
        label: 'Late Payments (12mo)',
        value: '0',
        impact: 'positive',
        weight: 0.45,
        description: 'Consistent on-time payer.',
      },
    ],
    actionItems: [
      {
        id: 'a003-1',
        priority: 'urgent',
        action: 'Address noise complaints — mediate with neighbors or reassign unit',
        owner: 'Property Manager',
        dueInDays: 3,
      },
      {
        id: 'a003-2',
        priority: 'high',
        action: 'Schedule 1:1 call to personally discuss concerns',
        owner: 'Leasing Manager',
        dueInDays: 2,
      },
      {
        id: 'a003-3',
        priority: 'medium',
        action: 'Offer unit transfer to quieter floor at same rate',
        owner: 'Leasing Agent',
        dueInDays: 7,
      },
    ],
  },
  {
    id: 'r004',
    name: 'Sandra Kim',
    unit: '8D',
    property: 'Greystar @ Midtown',
    leaseEndDate: '2025-06-15',
    monthlyRent: 2100,
    riskScore: 75,
    riskCategory: riskCategory(75),
    retentionVerdict: 'conditional',
    retentionRationale:
      'Moderate tenure, good payer. Retention feasible if rent increase is reduced and amenity issues resolved.',
    lifetimeValue: 25200,
    riskFactors: [
      {
        key: 'amenity_issues',
        label: 'Amenity Complaints',
        value: '2 filed',
        impact: 'negative',
        weight: 0.68,
        description: 'Pool and gym equipment complaints unresolved for over 3 weeks.',
      },
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+10%',
        impact: 'negative',
        weight: 0.70,
        description: 'Double-digit increase on a mid-tier unit is a high churn risk.',
      },
      {
        key: 'days_since_contact',
        label: 'Days Since Last Contact',
        value: '22 days',
        impact: 'neutral',
        weight: 0.25,
        description: 'Moderate gap since last leasing outreach.',
      },
      {
        key: 'tenure',
        label: 'Tenure',
        value: '2 years',
        impact: 'positive',
        weight: 0.30,
        description: 'Two-year tenure is a modest positive indicator.',
      },
    ],
    actionItems: [
      {
        id: 'a004-1',
        priority: 'urgent',
        action: 'Escalate pool and gym repair to vendor — set completion date',
        owner: 'Maintenance Team',
        dueInDays: 7,
      },
      {
        id: 'a004-2',
        priority: 'high',
        action: 'Offer renewal at +6% with amenity credit for delay',
        owner: 'Leasing Agent',
        dueInDays: 5,
      },
    ],
  },
  {
    id: 'r005',
    name: 'James Okafor',
    unit: '15F',
    property: 'Greystar @ Riverside',
    leaseEndDate: '2025-09-30',
    monthlyRent: 1750,
    riskScore: 71,
    riskCategory: riskCategory(71),
    retentionVerdict: 'conditional',
    retentionRationale:
      'Multiple late payments undercut retention value. Worth retaining only if payment behavior improves.',
    lifetimeValue: 21000,
    riskFactors: [
      {
        key: 'late_payments',
        label: 'Late Payments (12mo)',
        value: '4',
        impact: 'negative',
        weight: 0.85,
        description: '4 late payments in 12 months — significantly above property average of 0.8.',
      },
      {
        key: 'open_work_orders',
        label: 'Open Work Orders',
        value: '2 unresolved',
        impact: 'negative',
        weight: 0.40,
        description: 'Dishwasher and window seal tickets open for 12+ days.',
      },
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+7%',
        impact: 'negative',
        weight: 0.35,
        description: 'Moderate increase but resident may struggle given payment history.',
      },
      {
        key: 'app_engagement',
        label: 'App Engagement',
        value: 'High (51 sessions/mo)',
        impact: 'positive',
        weight: 0.55,
        description: 'Active resident portal user — frequently checks offers and interacts with partner promotions.',
      },
      {
        key: 'ad_interaction',
        label: 'Partner Offer Engagement',
        value: '5 offers redeemed',
        impact: 'positive',
        weight: 0.30,
        description: 'Redeemed 5 Uber Eats and partner offers in the last 90 days — high platform stickiness.',
      },
    ],
    actionItems: [
      {
        id: 'a005-1',
        priority: 'high',
        action: 'Discuss payment plan options before presenting renewal offer',
        owner: 'Leasing Manager',
        dueInDays: 5,
      },
      {
        id: 'a005-2',
        priority: 'high',
        action: 'Resolve dishwasher and window seal tickets',
        owner: 'Maintenance Team',
        dueInDays: 7,
      },
      {
        id: 'a005-3',
        priority: 'medium',
        action: 'Offer flexible rent payment schedule at renewal',
        owner: 'Leasing Agent',
        dueInDays: 10,
      },
    ],
  },
  {
    id: 'r006',
    name: 'Aaliyah Torres',
    unit: '3A',
    property: 'Greystar @ Midtown',
    leaseEndDate: '2025-07-15',
    monthlyRent: 2400,
    riskScore: 64,
    riskCategory: riskCategory(64),
    retentionVerdict: 'yes',
    retentionRationale:
      'Strong tenure, near-perfect payment history. Modest rent increase should secure renewal.',
    lifetimeValue: 28800,
    riskFactors: [
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+8%',
        impact: 'negative',
        weight: 0.62,
        description: 'Above average increase for this property tier.',
      },
      {
        key: 'days_since_contact',
        label: 'Days Since Last Contact',
        value: '30 days',
        impact: 'negative',
        weight: 0.38,
        description: 'Due for outreach — no contact in 30 days.',
      },
      {
        key: 'late_payments',
        label: 'Late Payments (12mo)',
        value: '1',
        impact: 'neutral',
        weight: 0.20,
        description: 'One minor late payment — low weight signal.',
      },
      {
        key: 'tenure',
        label: 'Tenure',
        value: '3.5 years',
        impact: 'positive',
        weight: 0.65,
        description: 'Long tenure with consistent lease renewals historically.',
      },
      {
        key: 'app_engagement',
        label: 'App Engagement',
        value: 'High (58 sessions/mo)',
        impact: 'positive',
        weight: 0.55,
        description: 'Consistent portal usage and high interaction with partner offers.',
      },
      {
        key: 'ad_interaction',
        label: 'Partner Offer Engagement',
        value: '7 offers redeemed',
        impact: 'positive',
        weight: 0.40,
        description: 'Regularly redeems Uber Eats and other partner promotions — strong platform attachment.',
      },
    ],
    actionItems: [
      {
        id: 'a006-1',
        priority: 'high',
        action: 'Send personalized renewal letter with loyalty appreciation',
        owner: 'Leasing Agent',
        dueInDays: 5,
      },
      {
        id: 'a006-2',
        priority: 'medium',
        action: 'Offer early-bird renewal discount if signed within 30 days',
        owner: 'Leasing Manager',
        dueInDays: 7,
      },
    ],
  },
  {
    id: 'r007',
    name: 'Tyler Reeves',
    unit: '7G',
    property: 'Greystar @ The Pines',
    leaseEndDate: '2025-08-15',
    monthlyRent: 1680,
    riskScore: 58,
    riskCategory: riskCategory(58),
    retentionVerdict: 'conditional',
    retentionRationale:
      'Recent job change flagged via application update. Financial uncertainty may drive non-renewal.',
    lifetimeValue: 20160,
    riskFactors: [
      {
        key: 'income_change',
        label: 'Income Change',
        value: 'Job change reported',
        impact: 'negative',
        weight: 0.75,
        description: 'Resident updated employer info — possible income instability.',
      },
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+6%',
        impact: 'negative',
        weight: 0.40,
        description: 'Market-rate increase, but risky given income uncertainty.',
      },
      {
        key: 'late_payments',
        label: 'Late Payments (12mo)',
        value: '2',
        impact: 'negative',
        weight: 0.45,
        description: '2 late payments — possibly correlated with income change.',
      },
      {
        key: 'tenure',
        label: 'Tenure',
        value: '2 years',
        impact: 'positive',
        weight: 0.30,
        description: 'Moderate tenure — some attachment to property.',
      },
    ],
    actionItems: [
      {
        id: 'a007-1',
        priority: 'high',
        action: 'Initiate sensitive conversation about financial situation',
        owner: 'Leasing Manager',
        dueInDays: 5,
      },
      {
        id: 'a007-2',
        priority: 'medium',
        action: 'Explore shorter-term lease or reduced renewal rate as bridge',
        owner: 'Leasing Agent',
        dueInDays: 10,
      },
    ],
  },
  {
    id: 'r008',
    name: 'Fatima Yusuf',
    unit: '9B',
    property: 'Greystar @ Riverside',
    leaseEndDate: '2025-06-30',
    monthlyRent: 2250,
    riskScore: 52,
    riskCategory: riskCategory(52),
    retentionVerdict: 'yes',
    retentionRationale:
      'Solid payment history and 2.5 years of tenure. Moderate risk driven mostly by rent increase — reducible with a small concession.',
    lifetimeValue: 27000,
    riskFactors: [
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+9%',
        impact: 'negative',
        weight: 0.60,
        description: 'Primary risk driver — slightly above market for this unit type.',
      },
      {
        key: 'open_work_orders',
        label: 'Open Work Orders',
        value: '1 unresolved',
        impact: 'negative',
        weight: 0.25,
        description: 'Minor plumbing issue pending 8 days.',
      },
      {
        key: 'late_payments',
        label: 'Late Payments (12mo)',
        value: '0',
        impact: 'positive',
        weight: 0.55,
        description: 'Flawless payment history.',
      },
      {
        key: 'tenure',
        label: 'Tenure',
        value: '2.5 years',
        impact: 'positive',
        weight: 0.40,
        description: 'Good tenure length with consistent renewals.',
      },
    ],
    actionItems: [
      {
        id: 'a008-1',
        priority: 'high',
        action: 'Cap rent increase at 7% and send offer by end of week',
        owner: 'Leasing Agent',
        dueInDays: 5,
      },
      {
        id: 'a008-2',
        priority: 'medium',
        action: 'Resolve plumbing ticket before renewal conversation',
        owner: 'Maintenance Team',
        dueInDays: 3,
      },
    ],
  },
  {
    id: 'r009',
    name: 'Carlos Mendez',
    unit: '1A',
    property: 'Greystar @ Midtown',
    leaseEndDate: '2025-10-31',
    monthlyRent: 3500,
    riskScore: 45,
    riskCategory: riskCategory(45),
    retentionVerdict: 'yes',
    retentionRationale:
      'Highest-value resident with exemplary payment history. Very likely to renew — standard outreach sufficient.',
    lifetimeValue: 42000,
    riskFactors: [
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+7%',
        impact: 'negative',
        weight: 0.48,
        description: 'Moderate increase for a premium unit.',
      },
      {
        key: 'days_since_contact',
        label: 'Days Since Last Contact',
        value: '25 days',
        impact: 'neutral',
        weight: 0.20,
        description: 'Approaching time for standard renewal outreach.',
      },
      {
        key: 'late_payments',
        label: 'Late Payments (12mo)',
        value: '0',
        impact: 'positive',
        weight: 0.70,
        description: 'Perfect payment history across entire tenancy.',
      },
      {
        key: 'tenure',
        label: 'Tenure',
        value: '5 years',
        impact: 'positive',
        weight: 0.80,
        description: 'Five-year tenure is a very strong retention indicator.',
      },
      {
        key: 'app_engagement',
        label: 'App Engagement',
        value: 'Moderate (34 sessions/mo)',
        impact: 'positive',
        weight: 0.35,
        description: 'Steady portal usage with occasional partner offer interaction.',
      },
      {
        key: 'ad_interaction',
        label: 'Partner Offer Engagement',
        value: '3 offers redeemed',
        impact: 'positive',
        weight: 0.25,
        description: 'Has redeemed a few Uber Eats offers — moderate platform engagement.',
      },
    ],
    actionItems: [
      {
        id: 'a009-1',
        priority: 'medium',
        action: 'Send standard 90-day renewal notice with VIP loyalty offer',
        owner: 'Leasing Agent',
        dueInDays: 14,
      },
    ],
  },
  {
    id: 'r010',
    name: 'Brenda Walsh',
    unit: '6C',
    property: 'Greystar @ The Pines',
    leaseEndDate: '2025-07-31',
    monthlyRent: 1900,
    riskScore: 40,
    riskCategory: riskCategory(40),
    retentionVerdict: 'yes',
    retentionRationale:
      'Long-term resident with stable history. Low risk — renewal expected without significant concessions.',
    lifetimeValue: 22800,
    riskFactors: [
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+5%',
        impact: 'neutral',
        weight: 0.30,
        description: 'Below-market increase — well within acceptable range.',
      },
      {
        key: 'open_work_orders',
        label: 'Open Work Orders',
        value: '0',
        impact: 'positive',
        weight: 0.40,
        description: 'All maintenance requests resolved promptly.',
      },
      {
        key: 'late_payments',
        label: 'Late Payments (12mo)',
        value: '0',
        impact: 'positive',
        weight: 0.60,
        description: 'On-time payer every month.',
      },
      {
        key: 'tenure',
        label: 'Tenure',
        value: '4 years',
        impact: 'positive',
        weight: 0.70,
        description: 'Strong tenure with two prior renewals.',
      },
    ],
    actionItems: [
      {
        id: 'a010-1',
        priority: 'low',
        action: 'Send standard renewal notice at 90-day mark',
        owner: 'Leasing Agent',
        dueInDays: 21,
      },
    ],
  },
  {
    id: 'r011',
    name: 'Eli Shapiro',
    unit: '11E',
    property: 'Greystar @ Riverside',
    leaseEndDate: '2025-11-30',
    monthlyRent: 2050,
    riskScore: 33,
    riskCategory: riskCategory(33),
    retentionVerdict: 'yes',
    retentionRationale:
      'Stable, low-maintenance resident. Renewal expected with standard process.',
    lifetimeValue: 24600,
    riskFactors: [
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+4%',
        impact: 'neutral',
        weight: 0.25,
        description: 'Below-market increase, unlikely to cause churn.',
      },
      {
        key: 'days_since_contact',
        label: 'Days Since Last Contact',
        value: '35 days',
        impact: 'neutral',
        weight: 0.20,
        description: 'Routine outreach window.',
      },
      {
        key: 'late_payments',
        label: 'Late Payments (12mo)',
        value: '0',
        impact: 'positive',
        weight: 0.55,
        description: 'Consistent, on-time payments.',
      },
      {
        key: 'tenure',
        label: 'Tenure',
        value: '3 years',
        impact: 'positive',
        weight: 0.60,
        description: 'Three renewals completed with no issues.',
      },
    ],
    actionItems: [
      {
        id: 'a011-1',
        priority: 'low',
        action: 'Send early renewal offer as a courtesy',
        owner: 'Leasing Agent',
        dueInDays: 30,
      },
    ],
  },
  {
    id: 'r012',
    name: 'Nina Patel',
    unit: '5D',
    property: 'Greystar @ Midtown',
    leaseEndDate: '2025-08-31',
    monthlyRent: 2300,
    riskScore: 21,
    riskCategory: riskCategory(21),
    retentionVerdict: 'yes',
    retentionRationale:
      'Highly engaged, long-tenure resident. Renewal is near-certain — maintain positive relationship.',
    lifetimeValue: 27600,
    riskFactors: [
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+4%',
        impact: 'neutral',
        weight: 0.18,
        description: 'Minimal increase, within resident expectation range.',
      },
      {
        key: 'open_work_orders',
        label: 'Open Work Orders',
        value: '0',
        impact: 'positive',
        weight: 0.35,
        description: 'Zero open tickets — maintenance satisfaction is high.',
      },
      {
        key: 'late_payments',
        label: 'Late Payments (12mo)',
        value: '0',
        impact: 'positive',
        weight: 0.65,
        description: 'Perfect payment record since move-in.',
      },
      {
        key: 'tenure',
        label: 'Tenure',
        value: '5+ years',
        impact: 'positive',
        weight: 0.85,
        description: 'Longest-tenure resident in the cohort. Extremely strong retention signal.',
      },
      {
        key: 'app_engagement',
        label: 'App Engagement',
        value: 'Very High (90+ sessions/mo)',
        impact: 'positive',
        weight: 0.75,
        description: 'Highest portal usage in the cohort — daily logins, power user of resident features.',
      },
      {
        key: 'ad_interaction',
        label: 'Partner Offer Engagement',
        value: '14 offers redeemed',
        impact: 'positive',
        weight: 0.55,
        description: 'Top partner offer redeemer — Uber Eats, grocery, and local perks. Extremely high platform stickiness.',
      },
    ],
    actionItems: [
      {
        id: 'a012-1',
        priority: 'low',
        action: 'Send VIP appreciation gift and renewal offer 90 days out',
        owner: 'Community Manager',
        dueInDays: 45,
      },
    ],
  },
  {
    id: 'r013',
    name: 'Reggie Foster',
    unit: '14B',
    property: 'Greystar @ The Pines',
    leaseEndDate: '2025-06-15',
    monthlyRent: 1820,
    riskScore: 91,
    riskCategory: riskCategory(91),
    retentionVerdict: 'no',
    retentionRationale:
      'Chronic late payments, 5 open work orders, and a formal complaint on file. Retention unlikely and not recommended.',
    lifetimeValue: 21840,
    riskFactors: [
      {
        key: 'late_payments',
        label: 'Late Payments (12mo)',
        value: '7',
        impact: 'negative',
        weight: 0.95,
        description: '7 late payments — well above threshold. Financial instability likely.',
      },
      {
        key: 'open_work_orders',
        label: 'Open Work Orders',
        value: '5 unresolved',
        impact: 'negative',
        weight: 0.80,
        description: '5 open tickets, 3 over 45 days. Repeated scheduling refusals by resident.',
      },
      {
        key: 'formal_complaint',
        label: 'Formal Complaint',
        value: '1 filed against',
        impact: 'negative',
        weight: 0.88,
        description: 'Formal noise complaint filed by 3 neighbors — pending resolution.',
      },
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+8%',
        impact: 'negative',
        weight: 0.42,
        description: 'Increase compounds existing financial stress.',
      },
    ],
    actionItems: [
      {
        id: 'a013-1',
        priority: 'urgent',
        action: 'Consult legal on non-renewal notice timeline',
        owner: 'Property Manager',
        dueInDays: 3,
      },
      {
        id: 'a013-2',
        priority: 'high',
        action: 'Document all open work order access refusals for file',
        owner: 'Maintenance Team',
        dueInDays: 5,
      },
    ],
  },
  {
    id: 'r014',
    name: 'Sophie Laurent',
    unit: '2F',
    property: 'Greystar @ Riverside',
    leaseEndDate: '2025-09-15',
    monthlyRent: 2750,
    riskScore: 67,
    riskCategory: riskCategory(67),
    retentionVerdict: 'yes',
    retentionRationale:
      'High-value unit, great payment record. Risk is driven by low app engagement and above-market rent increase — re-engage via partner offers and present a modest concession.',
    lifetimeValue: 33000,
    riskFactors: [
      {
        key: 'app_engagement',
        label: 'App Engagement',
        value: 'Low (7 sessions/mo)',
        impact: 'negative',
        weight: 0.72,
        description: 'Sharp drop in portal activity over the last 60 days — no partner offer clicks, minimal login.',
      },
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+8%',
        impact: 'negative',
        weight: 0.60,
        description: 'Above-market increase for this unit tier — compounds disengagement risk.',
      },
      {
        key: 'late_payments',
        label: 'Late Payments (12mo)',
        value: '0',
        impact: 'positive',
        weight: 0.55,
        description: 'Excellent payer — zero late fees.',
      },
      {
        key: 'tenure',
        label: 'Tenure',
        value: '2 years',
        impact: 'positive',
        weight: 0.35,
        description: 'Moderate tenure, switched from previous Greystar property.',
      },
    ],
    actionItems: [
      {
        id: 'a014-1',
        priority: 'urgent',
        action: 'Push personalized Uber Eats offer via app to re-engage — follow up with renewal call',
        owner: 'Leasing Manager',
        dueInDays: 3,
      },
      {
        id: 'a014-2',
        priority: 'high',
        action: 'Offer renewal at +5% with free parking for 6 months',
        owner: 'Leasing Agent',
        dueInDays: 5,
      },
    ],
  },
  {
    id: 'r015',
    name: 'David Okonkwo',
    unit: '10C',
    property: 'Greystar @ Midtown',
    leaseEndDate: '2025-07-31',
    monthlyRent: 2000,
    riskScore: 48,
    riskCategory: riskCategory(48),
    retentionVerdict: 'yes',
    retentionRationale: 'Stable resident with no red flags. Standard renewal process expected to succeed.',
    lifetimeValue: 24000,
    riskFactors: [
      {
        key: 'rent_increase',
        label: 'Rent Increase',
        value: '+6%',
        impact: 'neutral',
        weight: 0.35,
        description: 'Market-rate increase.',
      },
      {
        key: 'days_since_contact',
        label: 'Days Since Last Contact',
        value: '20 days',
        impact: 'neutral',
        weight: 0.20,
        description: 'Normal contact cadence.',
      },
      {
        key: 'late_payments',
        label: 'Late Payments (12mo)',
        value: '1',
        impact: 'neutral',
        weight: 0.22,
        description: 'Single late payment — minor signal.',
      },
      {
        key: 'tenure',
        label: 'Tenure',
        value: '2.5 years',
        impact: 'positive',
        weight: 0.50,
        description: 'Consistent renter with two prior renewals.',
      },
    ],
    actionItems: [
      {
        id: 'a015-1',
        priority: 'medium',
        action: 'Send renewal offer 90 days before lease end',
        owner: 'Leasing Agent',
        dueInDays: 14,
      },
    ],
  },
];

export function getResidentById(id: string): Resident | undefined {
  return residents.find((r) => r.id === id);
}

export const properties = [...new Set(residents.map((r) => r.property))];

export function getResidentProperty(resident: Resident): PropertyMeta {
  return propertyMeta[resident.property] ?? propertyMeta['Greystar @ Riverside'];
}
